### ISSUE TITLE
Exported executable doesn't work with the latest Shader Minifier `v1.3.6`

### ISSUE THREAD

**Issue by 0b5vr** [yosshin4004/minimal_gl#4]
最新のShader Minifier `v1.3.6` を使って「Export Executable」を行ったところ、ビルド成果物にシェーダのコードが含まれていないようです。
Crinklerを見てもどこにもシェーダコードがない。

`v1.2` では問題なく動くようです。

それぞれの出力された `.inl` を覗いてみたところ、新しいバージョンになって `#ifndef SHADER_MINIFIER_IMPL` という記述が増えているようです。

https://gist.github.com/0b5vr/843fffdec25b00d499d994bd406af0f9

どうやら、以下のPR（ `v1.3.5` ）で破壊的変更が入ったっぽいですね。

https://github.com/laurentlb/Shader_Minifier/pull/304

**Comment by 0b5vr** [comment]
`src/resource/resource.cpp` の最初の方、たとえば11行目に `#define SHADER_MINIFIER_IMPL` を入れると、後方互換性を保ったまま直せるようです。
とりあえずその方針でPRを出しておきましたが、これで良いか確信度低いので、方針について要望があればお伺いします。

https://github.com/yosshin4004/minimal_gl/pull/5

**Comment by yosshin4004** [comment]
shader_minifier の更新で、minify 前のシンボル名の取り方まわりが改良されたのですね。
ご提案いただいている resource.cpp で SHADER_MINIFIER_IMPL を define する方法で全く問題ございません。
