### ISSUE TITLE
Set no-renaming-list of Shader Minifier

### ISSUE THREAD

**Issue by 0b5vr** [yosshin4004/minimal_gl#6]
### Description

Shader Minifierの `--no-renaming-list` を渡したいです。
Export executableのダイアログのShader minifier optionsに対して、renameしたくないトークンをカンマ区切りで渡せるようなテキストボックスがあれば十分だと思います。

for文の添字に `i` しか使っていない場合など、 `--no-renaming-list main,i` を渡すと効率よく圧縮がされます。

no-renaming-listは、デフォルトでは `main,mainImage` が指定されているようなので、minimalGLとしてはデフォルト値に `main` を持っておくと良さそうです。

https://github.com/laurentlb/Shader_Minifier/blob/8bce238db39e288d5ae0e818471b68ba313e9399/src/options.fs#L102

### Workaround

現状は、自分でminimalGLをビルドする環境が整っている場合、 `export_executable.cpp` の `shaderMinifierOptions` に対して `--no-renaming-list main,i ` を追記しハードコードすることで対処可能です。

https://github.com/yosshin4004/minimal_gl/blob/e7bbaa2a4dcf02d4ba69b49a9630680ef1f51b09/src/export_executable.cpp#L517

**Comment by yosshin4004** [comment]
https://github.com/yosshin4004/minimal_gl/commit/d7aaadc4b40cf67a15e7316401ff5b9978aa7834
で対応しました。
"Export exectable" の UI に --no-renaming-list のチェックボックスとリストのエディットボックスが追加されています。

**Comment by 0b5vr** [comment]
手元で試して問題なく動きました！ありがとうございます！
本Issueは達成されたため、クローズします。
